# Generated by Django 5.2 on 2025-04-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('category', models.CharField(choices=[('Color', 'Color'), ('Color and Haircut', 'Color and Haircut'), ('Hair Treatments', 'Hair Treatments'), ('Haircuts', 'Haircuts'), ('Nail Treatments', 'Nail Treatments'), ('Facials', 'Facials'), ('Waxing', 'Waxing'), ('All Treatments', 'All Treatments')], max_length=50)),
                ('appointment_time', models.TimeField()),
                ('appointment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=20)),
                ('pimage', models.ImageField(default='', upload_to='pimage/')),
            ],
        ),
    ]
