# Generated by Django 5.2 on 2025-05-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('route_type', models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], max_length=10)),
                ('distance_km', models.PositiveIntegerField()),
                ('pass_type', models.CharField(choices=[('Local', 'Local'), ('Express', 'Express')], max_length=10)),
                ('duration_months', models.PositiveIntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='pass_photos/')),
                ('light_bill', models.ImageField(upload_to='light_bills/')),
                ('aadhaar', models.ImageField(upload_to='aadhaar_cards/')),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=10)),
            ],
        ),
    ]
