# Generated by Django 5.2 on 2025-05-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_passengerpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerpass',
            name='aadhaar',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_cards/'),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='duration_months',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='light_bill',
            field=models.FileField(blank=True, null=True, upload_to='light_bills/'),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='mobile',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='pass_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='payment_mode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='route_type',
            field=models.CharField(max_length=20),
        ),
    ]
