# Generated by Django 5.2 on 2025-05-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_passengerpass_aadhaar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerpass',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='passengerpass',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='passengerpass',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='aadhaar',
            field=models.FileField(upload_to='Aadharcard/'),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='light_bill',
            field=models.FileField(upload_to='Light_bill/'),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='photo',
            field=models.ImageField(upload_to='Passport_photo/'),
        ),
    ]
