# Generated by Django 5.2 on 2025-05-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_passengerpass_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='pimage/'),
        ),
    ]
