# Generated by Django 5.2 on 2025-06-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_pimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentpass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('route_type', models.CharField(max_length=20)),
                ('distance_km', models.PositiveIntegerField()),
                ('pass_type', models.CharField(max_length=10)),
                ('duration_months', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='Passport_photo/')),
                ('light_bill', models.FileField(upload_to='Light_bill/')),
                ('aadhaar', models.FileField(upload_to='Aadharcard/')),
                ('payment_mode', models.CharField(max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='pimage',
            field=models.ImageField(blank=True, default='pimage/default_avatar.png', upload_to='pimage/'),
        ),
    ]
