# Generated by Django 5.2 on 2025-06-14 20:37

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_clgstudentpass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clgstudentpass',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='studentpass',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pimage',
        ),
        migrations.AddField(
            model_name='clgstudentpass',
            name='clg_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clgstudentpass',
            name='clg_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clgstudentpass',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clgstudentpass',
            name='ent_number',
            field=models.CharField(default='TEMP123', max_length=20),
        ),
        migrations.AddField(
            model_name='clgstudentpass',
            name='fee_receipt',
            field=models.FileField(default='documents/receipts/default.pdf', upload_to='documents/receipts/'),
        ),
        migrations.AddField(
            model_name='clgstudentpass',
            name='provisional',
            field=models.FileField(default='documents/provisionals/default.pdf', upload_to='documents/provisionals/'),
        ),
        migrations.AddField(
            model_name='clgstudentpass',
            name='sem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 14, 20, 34, 20, 821720, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpass',
            name='provisional',
            field=models.FileField(default='default_file.pdf', upload_to='school_provisional/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpass',
            name='roll_number',
            field=models.CharField(default='NA123', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpass',
            name='school_address',
            field=models.TextField(default='Unknown School Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpass',
            name='school_name',
            field=models.CharField(default='Unknown School', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpass',
            name='standard',
            field=models.IntegerField(default='10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='aadhaar',
            field=models.FileField(upload_to='aadhaar_docs/'),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='distance_km',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='duration_months',
            field=models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months')]),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='light_bill',
            field=models.FileField(upload_to='light_bills/'),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='pass_type',
            field=models.CharField(choices=[('Local', 'Local'), ('Express', 'Express')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='photo',
            field=models.ImageField(upload_to='student_photos/'),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='route_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentpass',
            name='aadhaar',
            field=models.FileField(upload_to='aadhaar_docs/'),
        ),
        migrations.AlterField(
            model_name='studentpass',
            name='distance_km',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentpass',
            name='duration_months',
            field=models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months')]),
        ),
        migrations.AlterField(
            model_name='studentpass',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='studentpass',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentpass',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentpass',
            name='light_bill',
            field=models.FileField(upload_to='light_bills/'),
        ),
        migrations.AlterField(
            model_name='studentpass',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentpass',
            name='pass_type',
            field=models.CharField(choices=[('Local', 'Local'), ('Express', 'Express')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentpass',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentpass',
            name='photo',
            field=models.ImageField(upload_to='student_photos/'),
        ),
        migrations.AlterField(
            model_name='studentpass',
            name='route_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], max_length=10),
        ),
    ]
