# Generated by Django 5.2 on 2025-06-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_clgstudentpass_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clgstudentpass',
            name='aadhaar',
            field=models.FileField(upload_to='documents/aadhaars/'),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='clg_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='clg_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='duration_months',
            field=models.CharField(choices=[('1', '1 Month'), ('3', '3 Months'), ('6', '6 Months')], max_length=2),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='ent_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='fee_receipt',
            field=models.FileField(upload_to='documents/receipts/'),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='light_bill',
            field=models.FileField(upload_to='documents/light_bills/'),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='pass_type',
            field=models.CharField(choices=[('Local', 'Local'), ('Express', 'Express')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='photo',
            field=models.ImageField(upload_to='passports/'),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='provisional',
            field=models.FileField(upload_to='documents/provisionals/'),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='route_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clgstudentpass',
            name='sem',
            field=models.CharField(max_length=5),
        ),
    ]
