# Generated by Django 5.2 on 2025-06-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_clgstudentpass_aadhaar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clgStudentpass',
        ),
        migrations.DeleteModel(
            name='Studentpass',
        ),
        migrations.RemoveField(
            model_name='passengerpass',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='aadhaar',
            field=models.FileField(upload_to='uploads/aadhaar/'),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='distance_km',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='light_bill',
            field=models.FileField(upload_to='uploads/bills/'),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='pass_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='payment_mode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='photo',
            field=models.FileField(upload_to='uploads/photos/'),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='route_type',
            field=models.CharField(max_length=50),
        ),
    ]
