# Generated by Django 5.2 on 2025-06-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_clgstudentpass_delete_studentpass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerpass',
            name='payment_mode',
        ),
    ]
