# Generated by Django 5.2 on 2025-06-26 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_passengerpass_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerpass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='aadhaar',
            field=models.FileField(upload_to='documents/aadhaars/'),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='light_bill',
            field=models.FileField(upload_to='documents/light_bills/'),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='pass_type',
            field=models.CharField(choices=[('Local', 'Local'), ('Express', 'Express')], max_length=20),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='route_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], max_length=20),
        ),
    ]
