# Generated by Django 5.2 on 2025-06-26 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_passengerpass_created_at_alter_passengerpass_aadhaar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeStudentPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('Single', 'Single'), ('Multiple', 'Multiple')], max_length=20)),
                ('ent_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('clg_name', models.CharField(max_length=255)),
                ('clg_address', models.TextField()),
                ('sem', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('distance_km', models.FloatField()),
                ('pass_type', models.CharField(choices=[('Local', 'Local'), ('Express', 'Express')], max_length=20)),
                ('duration_months', models.CharField(choices=[('1', '1 Month'), ('3', '3 Months'), ('6', '6 Months')], max_length=2)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='uploads/photos/')),
                ('light_bill', models.FileField(upload_to='uploads/light_bills/')),
                ('aadhaar', models.FileField(upload_to='uploads/aadhaar/')),
                ('provisional', models.FileField(upload_to='uploads/provisional/')),
                ('fee_receipt', models.FileField(upload_to='uploads/fee_receipts/')),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='passengerpass',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
