# Generated by Django 5.2 on 2025-06-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_collegestudentpass_alter_passengerpass_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(max_length=20)),
                ('roll_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('school_name', models.CharField(max_length=200)),
                ('school_address', models.TextField()),
                ('standard', models.CharField(max_length=10)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pass_type', models.CharField(max_length=20)),
                ('duration_months', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('photo', models.ImageField(upload_to='student_photos/')),
                ('light_bill', models.FileField(upload_to='light_bills/')),
                ('aadhaar', models.FileField(upload_to='aadhaar_docs/')),
                ('provisional', models.FileField(upload_to='provisional_docs/')),
                ('payment_mode', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
